-- 1. Add order_distance_km to orders table
ALTER TABLE orders ADD COLUMN IF NOT EXISTS order_distance_km DOUBLE PRECISION;

-- 2. Create rider_tracking table for historical movement
CREATE TABLE IF NOT EXISTS rider_tracking (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id TEXT NOT NULL,
    rider_id TEXT NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable Realtime for rider_tracking
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'rider_tracking'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE rider_tracking;
    END IF;
END $$;

-- 4. Ensure vendors have latitude and longitude (Confirming existence/types)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='vendors' AND column_name='latitude') THEN
        ALTER TABLE vendors ADD COLUMN latitude DOUBLE PRECISION;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='vendors' AND column_name='longitude') THEN
        ALTER TABLE vendors ADD COLUMN longitude DOUBLE PRECISION;
    END IF;
END $$;
