-- Create platform_settings table
CREATE TABLE IF NOT EXISTS platform_settings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    key TEXT UNIQUE NOT NULL,
    value JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed platform_settings
INSERT INTO platform_settings (key, value)
VALUES ('config', '{
    "platformName": "UNIV Foods",
    "currency": "INR",
    "taxRate": 5,
    "platformFee": 15,
    "supportEmail": "support@univfoods.in",
    "maintenanceMode": false
}')
ON CONFLICT (key) DO NOTHING;

-- Create audit_logs table
CREATE TABLE IF NOT EXISTS audit_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    action TEXT NOT NULL,
    admin_user TEXT NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    metadata JSONB
);

-- Enable Realtime
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'platform_settings'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE platform_settings;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'audit_logs'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE audit_logs;
    END IF;

    -- Add remaining admin tables
    FOR tab IN (SELECT unnest(ARRAY['payments', 'payment_rules', 'registrations', 'vendors', 'products', 'categories', 'banners'])) LOOP
        IF NOT EXISTS (
            SELECT 1 FROM pg_publication_tables 
            WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = tab
        ) THEN
            EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE %I', tab);
        END IF;
    END LOOP;
END $$;
